package lazy.tests;

import lazy.Lazy;
import lazy.LazyFactory;

import java.util.function.Supplier;

/**
 * Test set for lock-free thread-safe implementation of {@link lazy.Lazy}
 * generated by {@link lazy.LazyFactory#createLazyLockFree(Supplier)}
 */
public class LockFreeLazyTest extends MultiThreadedLazyTest {

    @Override
    protected <T> Lazy<T> applyLazyFactoryGenerator(Supplier<T> supplier) {
        return LazyFactory.createLazyLockFree(supplier);
    }
}
