package lazy.tests;

import lazy.Lazy;
import lazy.LazyFactory;

import java.util.function.Supplier;

/**
 * Test set for single-threaded implementation of {@link lazy.Lazy}
 * generated by {@link lazy.LazyFactory#createLazySingleThreaded(Supplier)}
 */
public class SingleThreadedLazyTest extends LazyTest {

    protected <T> Lazy<T> applyLazyFactoryGenerator(Supplier<T> supplier) {
        return LazyFactory.createLazySingleThreaded(supplier);
    }
}